version: '3.9'

services:
  hr-etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr-etl-app
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./app.db:/app/app.db
      - ./data:/app/data
      - ./database:/app/database
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
